#!/bin/bash

repo="$(pwd)"

anglerUrl="$(git config angler.url)"

while read update; do
    if [ -z "$updates" ]
    then
        updates=$update
    else
        updates=$updates$'\n'$update
    fi
done < /dev/stdin

res="$(curl -s --data "$updates" "$anglerUrl?hook=receive&repo=$repo")"

IFS=$'\n' respArgs=($res)

exitcode=${respArgs[0]}

for echoline in "${respArgs[@]:1}"
do
    echo $echoline
done

exit $exitcode

