var gulp = require('gulp'),
    browserify = require('browserify'),
    buffer = require('vinyl-buffer'),
    cache,
    concat = require('gulp-concat'),
    hbsfy = require('hbsfy'),
    livereload,
    nodeunit,
    plumber,
    prefixer = require('gulp-autoprefixer'),
    rimraf,
    sass = require('gulp-sass')(require('sass')),
    source = require('vinyl-source-stream'),
    // stylish,
    uglify = require('gulp-uglify'),

    production = process.env.NODE_ENV === 'production',

    path = {
        src: {
            all: 'src/**/*',
            js: 'src/**/*.js',
            client: {
                main: './src/client/js/main.js',
                scss: 'src/client/**/*.s[ac]ss',
                static: [
                    'src/client/resources/**/*',
                    'src/client/exercises/**/*',
                    'src/client/*.html'
                ]
            },
            exercises: 'node_modules/gitstream-exercises/exercises',
            server: 'src/server/**/*'
        },
        dist: {
            base: 'dist/',
            all: 'dist/**/*',
            client: 'dist/client/',
            server: 'dist/server/',
            exercises: 'dist/server'
        },
    }

if ( !production ) {
    cache = require('gulp-cached');
    livereload = require('gulp-livereload');
    //nodeunit = require('gulp-nodeunit');
    plumber = require('gulp-plumber');
    rimraf = require('rimraf');
}

// *~ is generated by vim as temp file when saving atomically
function notilde( path ) {
    return [].concat( path, '!**/*~' );
}

// todo: Convert to an npm script to compile Sass. Make use of the package `node-sass`
gulp.task( 'sass', function() {
    var stream = gulp.src( path.src.client.scss )

    if ( !production ) {
        stream = stream
            .pipe( plumber() )
    }

    return stream.pipe( sass() )
        //.pipe( minifyCss({ cache: true }) )
        .pipe( concat('bundle.css') )
        .pipe( prefixer('> 5%') )
        .pipe( gulp.dest( path.dist.client ) );
});


// todo: Convert to an npm script to bundle JS with `esbuild`
gulp.task( 'browserify', function() {
    var bundler = browserify({
        cache: {}, packageCache: {}, fullPaths: true,
        entries: path.src.client.main,
        debug: !production
    });

    var bundle = function() {
        var stream = bundler.bundle()
            .on( 'error', function( e ) {
                console.error( '\x1b[31;1m', 'Browserify Error', e.toString(), '\x1b[0m' );
            })
            .pipe( source('bundle.js') );

        if ( production ) {
            stream = stream
                .pipe( buffer() )
                //.pipe( uglify() )
        }

        stream.pipe( gulp.dest( path.dist.client ) );

        return stream;
    };

    return bundle();
});

// todo: Throw away, we can copy static assets as part of build
gulp.task( 'collectstatic', function() {
    var stream = gulp.src( notilde( path.src.client.static ) );

    if( !production ) {
        stream = stream.pipe( cache('static') );
    }

    return stream.pipe( gulp.dest( path.dist.client ) );
});

// todo: throw away, we can copy the server files as part of build
gulp.task( 'collectserver', function() {
    var stream = gulp.src( notilde( path.src.server ) )

    if( !production ) {
        stream = stream.pipe( cache('server') );
    }

    return stream.pipe( gulp.dest( path.dist.server ) );
});

// todo: throw away, we can create these symlinks as part of build
gulp.task( 'linkexercises', function() {
    return gulp.src( path.src.exercises )
        .pipe( gulp.symlink( path.dist.exercises , { overwrite: true, relativeSymlinks: true }) );
});

// todo: convert to makefile task to run build steps
gulp.task( 'build', gulp.series('sass', 'browserify', 'collectstatic', 'collectserver', 'linkexercises'), function build (cb) {
    cb();
});

// todo:  convert to makefile default task
gulp.task( 'default', gulp.series('build'), function defaultTask (cb) {
    cb();
});
