# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "gitstream"
  end

  #config.vm.box = "ubuntu/focal64" # Ubuntu 20
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  #config.vm.network "private_network", ip: "192.168.42.10"

  # config.vm.network "public_network", ip: "192.168.42.10"

  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "..", "/opt/gitstream"

  # Here be provisioners
  config.vm.provision "shell", path: "init.sh"
  config.vm.provision "shell", path: "startup.sh", run: "always"

  # Automatically cd to project folder 
  config.ssh.extra_args = ["-t", "cd /opt/gitstream; bash --login"]
end
